const $ = (selector) => document.querySelector(selector);
let token = localStorage.getItem('everlight-token') || '';
let currentUser = null;
let imageData = '', profileImageData = '', coverImageData = '';

function notify(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3000); }
function escapeHtml(text = '') { const node = document.createElement('div'); node.textContent = text; return node.innerHTML; }
async function api(url, options = {}) { const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Kapcsolati hiba.'); return data; }
function avatar(user, anonymous = false) { if (anonymous) return '<div class="avatar aurora">✦</div>'; if (user.avatar) return `<div class="avatar aurora profile-custom-image"><img src="${user.avatar}" alt="Profilkép"></div>`; return `<div class="avatar aurora">${escapeHtml((user.displayName || user.username || '?').charAt(0).toUpperCase())}</div>`; }
function setAccount(user) { if (!user) return; currentUser = user; const displayNameOrUsername = user.displayName || user.username || '?'; $('#profileAvatar').textContent = displayNameOrUsername.charAt(0).toUpperCase(); $('#profileAvatar').style.background = user.profileColor || '#273638'; if (user.avatar) { $('#profileAvatar').innerHTML = `<img src="${user.avatar}" alt="Profilkép">`; $('#profileAvatar').classList.add('profile-custom-image'); } $('#profileSummary').innerHTML = `<strong style="color:${user.nameColor || '#67e7dd'}">${escapeHtml(displayNameOrUsername)}</strong><br />${escapeHtml(user.bio || user.status || 'Elérhető')}`; $('#activityLocked').hidden = true; $('#activityStats').hidden = false; $('#profileSettings').hidden = false; $('#accountMenu').classList.add('logged-in'); $('#displayName').value = user.displayName || ''; $('#profileBio').value = user.bio || ''; $('#pronouns').value = user.pronouns || ''; $('#profileLocation').value = user.location || ''; $('#profileWebsite').value = user.website || ''; $('#profileStatus').value = user.status || '✦ Elérhető'; $('#nameColor').value = user.nameColor || '#67e7dd'; $('#profileColor').value = user.profileColor || '#273638'; profileImageData = user.avatar || ''; coverImageData = user.cover || ''; if (user.avatar) $('#profileImagePreview').innerHTML = `<img src="${user.avatar}" alt="Profilkép">`; if (user.cover) $('#coverPreview').style.backgroundImage = `url(${user.cover})`; }
function requireLogin() { if (currentUser) return true; $('#accountMenu').classList.add('open'); $('#accountButton').classList.add('active'); notify('Ehhez előbb jelentkezz be.'); return false; }
function renderPost(post) { const date = new Date(post.created_at).toLocaleTimeString('hu-HU', { hour: '2-digit', minute: '2-digit' }); const anonymous = Boolean(post.is_anonymous); const user = { username: post.username, displayName: post.display_name || post.username.split('#')[0], avatar: post.avatar || '' }; return `<article class="post"><div class="post-top"><div class="identity">${avatar(user, anonymous)}<div><strong>${anonymous ? 'Névtelen' : escapeHtml(user.displayName)}</strong><span>${anonymous ? '@anonymous' : '@' + escapeHtml(user.username)}</span></div></div><time>${date}</time></div>${post.body ? `<p>${escapeHtml(post.body)}</p>` : ''}${post.image ? `<img class="post-image" src="${post.image}" alt="Megosztott kép">` : ''}<div class="post-bottom"><span class="story-label">${escapeHtml(post.category).toUpperCase()}</span></div></article>`; }
async function loadPosts() { try { const { posts } = await api('/api/posts', { headers: {} }); $('#feedList').innerHTML = posts.length ? posts.map(renderPost).join('') : '<p class="loading-copy">Még nincs bejegyzés. Légy te az első.</p>'; } catch { $('#feedList').innerHTML = '<p class="loading-copy">Az áramlás nem érhető el. Ellenőrizd, hogy a Node szerver fut-e.</p>'; } }
async function loadOnline() { try { const { users } = await api('/api/online', { headers: {} }); $('#onlineCount').innerHTML = `<i></i> ${users.length}`; $('#onlineFaces').innerHTML = users.length ? users.map((user) => avatar({ ...user, displayName: user.display_name || user.username.split('#')[0] })).join('') : '<span class="loading-copy">Most nincs aktív felhasználó.</span>'; } catch { $('#onlineFaces').innerHTML = '<span class="loading-copy">Nincs kapcsolat.</span>'; } }

$('#accountButton').addEventListener('click', () => { const open = $('#accountMenu').classList.toggle('open'); $('#accountButton').classList.toggle('active', open); });
document.addEventListener('click', (event) => { if (!event.target.closest('.account-wrap')) { $('#accountMenu').classList.remove('open'); $('#accountButton').classList.remove('active'); } });
$('#loginForm').addEventListener('submit', async (event) => { event.preventDefault(); try { const data = await api('/api/auth/enter', { method: 'POST', body: JSON.stringify({ username: $('#loginName').value, email: $('#loginForm input[type=email]').value, password: $('#loginForm input[type=password]').value }) }); token = data.token; localStorage.setItem('everlight-token', token); setAccount(data.user); notify('Sikeres belépés.'); await Promise.all([loadPosts(), loadOnline()]); } catch (error) { notify(error.message); } });
$('#postText').addEventListener('input', () => $('#counter').textContent = `${$('#postText').value.length} / 280`);
$('#imageInput').addEventListener('change', () => { const file = $('#imageInput').files[0]; if (!file) return; if (file.size > 1024 * 1024) return notify('A kép legfeljebb 1 MB lehet.'); const reader = new FileReader(); reader.onload = () => { imageData = reader.result; $('#imagePreview').innerHTML = `<img src="${imageData}" alt="Előnézet"><button type="button">×</button>`; $('#imagePreview').classList.add('visible'); $('#imageName').textContent = file.name.slice(0, 16); }; reader.readAsDataURL(file); });
$('#imagePreview').addEventListener('click', (event) => { if (event.target.tagName === 'BUTTON') { imageData = ''; $('#imageInput').value = ''; $('#imagePreview').innerHTML = ''; $('#imagePreview').classList.remove('visible'); $('#imageName').textContent = 'Kép'; } });
$('#postButton').addEventListener('click', async () => { if (!requireLogin()) return; try { const { post } = await api('/api/posts', { method: 'POST', body: JSON.stringify({ body: $('#postText').value, category: $('#category').value, anonymous: $('#anonymous').checked, image: imageData }) }); $('#feedList').insertAdjacentHTML('afterbegin', renderPost(post)); $('#postText').value = ''; $('#counter').textContent = '0 / 280'; imageData = ''; $('#imageInput').value = ''; $('#imagePreview').innerHTML = ''; $('#imagePreview').classList.remove('visible'); $('#imageName').textContent = 'Kép'; $('#postCount').textContent = Number($('#postCount').textContent) + 1; notify('A bejegyzésed megjelent az áramlásban.'); await loadOnline(); } catch (error) { notify(error.message); } });
function readImage(input, callback) { const file = input.files[0]; if (!file) return; if (file.size > 1024 * 1024) return notify('A kép legfeljebb 1 MB lehet.'); const reader = new FileReader(); reader.onload = () => callback(reader.result); reader.readAsDataURL(file); }
$('#profileImageInput').addEventListener('change', () => readImage($('#profileImageInput'), (data) => { profileImageData = data; $('#profileImagePreview').innerHTML = `<img src="${data}" alt="Profilkép">`; }));
$('#coverImageInput').addEventListener('change', () => readImage($('#coverImageInput'), (data) => { coverImageData = data; $('#coverPreview').style.backgroundImage = `url(${data})`; }));
$('#saveProfile').addEventListener('click', async () => { if (!requireLogin()) return; try { const { user } = await api('/api/profile', { method: 'PUT', body: JSON.stringify({ displayName: $('#displayName').value, bio: $('#profileBio').value, avatar: profileImageData, cover: coverImageData, nameColor: $('#nameColor').value, profileColor: $('#profileColor').value, status: $('#profileStatus').value, pronouns: $('#pronouns').value, location: $('#profileLocation').value, website: $('#profileWebsite').value }) }); setAccount(user); notify('A profilod mentve lett.'); } catch (error) { notify(error.message); } });
$('#messageNav').addEventListener('click', (event) => { event.preventDefault(); if (!requireLogin()) return; $('#messages').classList.add('open'); }); 
$('#messagesHeaderButton').addEventListener('click', () => { if (!requireLogin()) return; $('#messages').classList.add('open'); }); 
$('#closeMessages').addEventListener('click', () => $('#messages').classList.remove('open'));
async function loadMessages() { const recipient = $('#dmRecipient').value.trim(); if (!recipient || !currentUser) return; try { const data = await api(`/api/messages/${encodeURIComponent(recipient)}`); if (data.user) $('#dmTitle').textContent = data.user.displayName || data.user.username || 'Ismeretlen'; $('#dmList').innerHTML = data.messages.length ? data.messages.map((m) => `<div class="dm"><div><strong>${escapeHtml(m.sender_name || m.sender_username)}</strong><p>${escapeHtml(m.body)}</p></div></div>`).join('') : '<p class="loading-copy">Még nincs üzenet.</p>'; } catch (error) { $('#dmList').innerHTML = `<p class="loading-copy">${escapeHtml(error.message)}</p>`; } }
$('#dmRecipient').addEventListener('change', loadMessages);
$('#messageForm').addEventListener('submit', async (event) => { event.preventDefault(); if (!requireLogin()) return; const recipient = $('#dmRecipient').value.trim(); try { await api(`/api/messages/${encodeURIComponent(recipient)}`, { method: 'POST', body: JSON.stringify({ body: $('#dmBody').value }) }); $('#dmBody').value = ''; await loadMessages(); notify('Üzenet elküldve.'); } catch (error) { notify(error.message); } });

window.addEventListener('beforeinstallprompt', (event) => { event.preventDefault(); window.everlightInstall = event; });
$('#installButton').addEventListener('click', async () => { if (!window.everlightInstall) return notify('iPhone: Safari → Megosztás → Főképernyőhöz adás. Android: böngésző menü → Telepítés.'); window.everlightInstall.prompt(); await window.everlightInstall.userChoice; window.everlightInstall = null; });
$('#notificationButton').addEventListener('click', async () => { if (!('Notification' in window)) return notify('Ez a böngésző nem támogatja az értesítéseket.'); notify((await Notification.requestPermission()) === 'granted' ? 'Értesítések engedélyezve.' : 'Az értesítések nem lettek engedélyezve.'); });
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js'));
(async () => { if (token) try { const { user } = await api('/api/auth/me'); setAccount(user); } catch { localStorage.removeItem('everlight-token'); token = ''; } await Promise.all([loadPosts(), loadOnline()]); setInterval(() => { loadOnline(); if (currentUser) loadMessages(); }, 30000); })();
